# permissions for end users to view servicemeshclasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: servicemeshclass-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: servicemesh-operator
    app.kubernetes.io/part-of: servicemesh-operator
    app.kubernetes.io/managed-by: kustomize
  name: servicemeshclass-viewer-role
rules:
- apiGroups:
  - rainbond.io
  resources:
  - servicemeshclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rainbond.io
  resources:
  - servicemeshclasses/status
  verbs:
  - get
