apiVersion: rainbond.io/v1alpha1
kind: ServiceMeshClass
metadata:
  labels:
    app.kubernetes.io/name: servicemeshclass
    app.kubernetes.io/instance: servicemeshclass-sample
    app.kubernetes.io/part-of: servicemesh-operator
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: servicemesh-operator
  name: servicemeshclass-sample
spec:
  # TODO(user): Add fields here
